# Machine Learning Seminar 2017 - MIM UW
### Workshop Anaconda + Jupyter + SciKit-learn + Pandas 
Michał Woś

### ANACONDA
* Download: środowisko Anaconda z Pythonem 2.7: https://www.anaconda.com/download/#linux
* `conda create --name ml-sem --file ml-sem-spec.txt` Stworzenie odseparowanego środowiska potrzebnego do tego notebooka (zainstaluje konieczne pakiety)
* `. activate ml-sem` aktywowanie odseparowanego środowiska
* `jupyter notebook` odpalenie notebooka - można także wyklikać w `anaconda-navigator`
* `conda install package_name` do doinstalowywania pakietów lub wygodne GUI do zarządzania całością `anaconda-navigator`

<img src="includes/anaconda1.png" />
<img src="includes/anaconda2.jpg" />
<img src="includes/anaconda3.jpg" />
<img src="includes/anaconda4.jpg" />
<img src="includes/anaconda5.jpg" />

* Czym jest? Pakiety, środowisko. Czym nie jest? Menadżerem konfiguracji, procesów.
* Izolacja oprogramowania, różnych jego wersji, które w innym przypadku mogłoby kolidować.
* Uproszczenie życia dla nieinformatycznych Data scientist.
* Wersja Enterprise zintegrowana z rozwiązaniami Cloudowymi i dockerem.
* GUI

### JUPYTER
##### Podstawowe polecenia
* `ctrl-enter` - wykonianie kodu komórki
* `ctrl-shift-enter` - wykonanie kodu komórki i przejście do następnej komórki/dodanie kolejnej komórki
* `tab` - uzupełnienie kodu
* `shift-tab` - pokaż sygnaturę funkcji

### PANDAS

In [138]:
import pandas as pd

### DataFrame
<img src="includes/dataframe.jpg" />

#### Tutoriale
* TL;DR https://pandas.pydata.org/pandas-docs/stable/10min.html
* Full: https://pandas.pydata.org/pandas-docs/stable/tutorials.html

In [139]:
pd.DataFrame({
    'letter': list('abcd'),
    'number': [1, 2, 3, 4]
})

  letter  number
0      a       1
1      b       2
2      c       3
3      d       4

In [140]:
df = pd.DataFrame(
    [
        ['a',   0.1,    1],
        ['b', '0.2', None],
        ['c',  None,    3],
        ['a',   1.5,    4],
    ],
    columns = ['litery', 'miks', 'liczby']
)
df

  litery  miks  liczby
0      a   0.1     1.0
1      b   0.2     NaN
2      c  None     3.0
3      a   1.5     4.0

In [141]:
print(type(df['litery']))
print(type(df[['litery']]))

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [142]:
df.at[1, 'miks']

'0.2'

In [143]:
df.loc[1:3,'miks']

1     0.2
2    None
3     1.5
Name: miks, dtype: object

In [144]:
print(df.dtypes)

litery     object
miks       object
liczby    float64
dtype: object

In [145]:
import numpy as np


print('Tylko numeryki:')
print(df.select_dtypes(include=[np.number]))
print('\nTylko nie numeryki:')
print(df.select_dtypes(exclude=[np.number]))

Tylko numeryki:
   liczby
0     1.0
1     NaN
2     3.0
3     4.0

Tylko nie numeryki:
  litery  miks
0      a   0.1
1      b   0.2
2      c  None
3      a   1.5

In [146]:
# Wyrażenia logiczne
df['litery'] == 'a'

0     True
1    False
2    False
3     True
Name: litery, dtype: bool

In [147]:
# Używanie logicznego wyrażenia do wybierania podzbioru
selector = df['litery'] == 'a'
df[selector]

  litery miks  liczby
0      a  0.1     1.0
3      a  1.5     4.0

In [148]:
df[(df['litery'] == 'a') & (df['liczby'] == 4)]

  litery miks  liczby
3      a  1.5     4.0

In [149]:
# Operacje na stringach
~df['litery'].str.contains('a')  # nie zawiera

0    False
1     True
2     True
3    False
Name: litery, dtype: bool

In [150]:
# Metoda apply - domyślnie nie modyfikuje oryginalnej ramki
counter = 0
def add_values(column):
    # column jest typu pandas.Series
    global counter  # NIE CZYŃ TAK!
    counter += 1
    return column + column


print('Wynik apply:')
print(df[df['litery'] == 'a'].apply(add_values))
print()
print('Oryginalny df:')
print(df)

Wynik apply:
  litery  miks  liczby
0     aa   0.2     2.0
3     aa   3.0     8.0
()
Oryginalny df:
  litery  miks  liczby
0      a   0.1     1.0
1      b   0.2     NaN
2      c  None     3.0
3      a   1.5     4.0

In [151]:
print(counter)

4

In [152]:
df.dropna(how='any')

  litery miks  liczby
0      a  0.1     1.0
3      a  1.5     4.0

In [153]:
# Metoda apply - operacje na wierszach
def add_values(row):
    row['litery'] = int(row['liczby'] * row['miks']) * row['litery']
    return row


df[df['litery'] == 'a'].apply(add_values, axis=1)  # domyślny parametr axis=0 -> operacje na kolumnach

   litery  miks  liczby
0           0.1     1.0
3  aaaaaa   1.5     4.0

In [154]:
# Modyfikacja wybranych wierszy w danej kolumnie: loc
df.loc[df['litery'] == 'a', 'litery'] = 'ww'

# nie tak, jesli chcesz zmieniac wartość!
# df['litery'][df['litery'] == 'a'] = 'b'

df

  litery  miks  liczby
0     ww   0.1     1.0
1      b   0.2     NaN
2      c  None     3.0
3     ww   1.5     4.0

#### Agregacje, grupowania, sortownaia, łączenia...

* Podpowiadanie komend `<tab>` - do pierwszej kropki przypisz na zmienną, wykonaj `ctrl-enter` potem `.` i `<tab>`

In [155]:
g = df.groupby('litery')
g.sum()

        liczby
litery
b          NaN
c          3.0
ww         5.0

In [156]:
df.sort_values(by='liczby', ascending=False)

  litery  miks  liczby
3     ww   1.5     4.0
2      c  None     3.0
0     ww   0.1     1.0
1      b   0.2     NaN

In [157]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})
right = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4, 5]})
pd.merge(left, right, on='key')

   key  lval  rval
0  foo     1     4
1  foo     2     4

### SKLEARN

##### Transformacje
* `fit(X, y=None, **fit_params)`
* `transform(X, y=None, **fit_params)`
* `fit_transform(X, y=None, **fit_params)`

Dane - Kaggle: https://www.kaggle.com/c/house-prices-advanced-regression-techniques

In [158]:
train = pd.read_csv('train.csv', index_col='Id')
y = train.pop('SalePrice')

test = pd.read_csv('test.csv', index_col='Id')
print(train.shape)
train.head(10)

(1460, 79)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1.5Fin,5,5,1993,1995,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,Wood,Gd,TA,No,GLQ,732,Unf,0,64,796,GasA,Ex,Y,SBrkr,796,566,0,1362,1,0,1,1,1,1,TA,5,Typ,0,NaN,Attchd,1993.0,Unf,2,480,TA,TA,Y,40,30,0,320,0,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal
7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,1Story,8,5,2004,2005,Gable,CompShg,VinylSd,VinylSd,Stone,186.0,Gd,TA,PConc,Ex,TA,Av,GLQ,1369,Unf,0,317,1686,GasA,Ex,Y,SBrkr,1694,0,0,1694,1,0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2004.0,RFn,2,636,TA,TA,Y,255,57,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,7,6,1973,1973,Gable,CompShg,HdBoard,HdBoard,Stone,240.0,TA,TA,CBlock,Gd,TA,Mn,ALQ,859,BLQ,32,216,1107,GasA,Ex,Y,SBrkr,1107,983,0,2090,1,0,2,1,3,1,TA,7,Typ,2,TA,Attchd,1973.0,RFn,2,484,TA,TA,Y,235,204,228,0,0,0,NaN,NaN,Shed,350,11,2009,WD,Normal
9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Artery,Norm,1Fam,1.5Fin,7,5,1931,1950,Gable,CompShg,BrkFace,Wd Shng,None,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0,Unf,0,952,952,GasA,Gd,Y,FuseF,1022,752,0,1774,0,0,2,0,2,2,TA,8,Min1,2,TA,Detchd,1931.0,Unf,2,468,Fa,TA,Y,90,0,205,0,0,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml
10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,BrkSide,Artery,Artery,2fmCon,1.5Unf,5,6,1939,1950,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,BrkTil,TA,TA,No,GLQ,851,Unf,0,140,991,GasA,Ex,Y,SBrkr,1077,0,0,1077,1,0,1,0,2,2,TA,5,Typ,2,TA,Attchd,1939.0,RFn,1,205,Gd,TA,Y,0,4,0,0,0,0,NaN,NaN,NaN,0,1,2008,WD,Normal

In [159]:
train.columns

Index([u'MSSubClass', u'MSZoning', u'LotFrontage', u'LotArea', u'Street',
       u'Alley', u'LotShape', u'LandContour', u'Utilities', u'LotConfig',
       u'LandSlope', u'Neighborhood', u'Condition1', u'Condition2',
       u'BldgType', u'HouseStyle', u'OverallQual', u'OverallCond',
       u'YearBuilt', u'YearRemodAdd', u'RoofStyle', u'RoofMatl',
       u'Exterior1st', u'Exterior2nd', u'MasVnrType', u'MasVnrArea',
       u'ExterQual', u'ExterCond', u'Foundation', u'BsmtQual', u'BsmtCond',
       u'BsmtExposure', u'BsmtFinType1', u'BsmtFinSF1', u'BsmtFinType2',
       u'BsmtFinSF2', u'BsmtUnfSF', u'TotalBsmtSF', u'Heating', u'HeatingQC',
       u'CentralAir', u'Electrical', u'1stFlrSF', u'2ndFlrSF', u'LowQualFinSF',
       u'GrLivArea', u'BsmtFullBath', u'BsmtHalfBath', u'FullBath',
       u'HalfBath', u'BedroomAbvGr', u'KitchenAbvGr', u'KitchenQual',
       u'TotRmsAbvGrd', u'Functional', u'Fireplaces', u'FireplaceQu',
       u'GarageType', u'GarageYrBlt', u'GarageFinish', u'GarageCars',
       u'GarageArea', u'GarageQual', u'GarageCond', u'PavedDrive',
       u'WoodDeckSF', u'OpenPorchSF', u'EnclosedPorch', u'3SsnPorch',
       u'ScreenPorch', u'PoolArea', u'PoolQC', u'Fence', u'MiscFeature',
       u'MiscVal', u'MoSold', u'YrSold', u'SaleType', u'SaleCondition'],
      dtype='object')

In [160]:
pd.set_option('display.max_columns', None)
train.select_dtypes(include=[np.number]).loc[1:5,:]

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
Id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706,0,150,856,856,854,0,1710,1,0,2,1,3,1,8,0,2003.0,2,548,0,61,0,0,0,0,0,2,2008
2,20,80.0,9600,6,8,1976,1976,0.0,978,0,284,1262,1262,0,0,1262,0,1,2,0,3,1,6,1,1976.0,2,460,298,0,0,0,0,0,0,5,2007
3,60,68.0,11250,7,5,2001,2002,162.0,486,0,434,920,920,866,0,1786,1,0,2,1,3,1,6,1,2001.0,2,608,0,42,0,0,0,0,0,9,2008
4,70,60.0,9550,7,5,1915,1970,0.0,216,0,540,756,961,756,0,1717,1,0,1,0,3,1,7,1,1998.0,3,642,0,35,272,0,0,0,0,2,2006
5,60,84.0,14260,8,5,2000,2000,350.0,655,0,490,1145,1145,1053,0,2198,1,0,2,1,4,1,9,1,2000.0,3,836,192,84,0,0,0,0,0,12,2008

In [161]:
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.preprocessing import FunctionTransformer, MinMaxScaler
# uwaga, to nie jest enkoder ze scikit, ale implementuje jego API, wiec mozna uzywac!
from category_encoders.one_hot import OneHotEncoder
from sklearn.base import TransformerMixin

In [162]:
# train['MSSubClass'] = train['MSSubClass'].astype(str)
# to samo dla test
# ..albo:

def fix_type(df):
    df['MSSubClass'] = df['MSSubClass'].astype(str)
    return df

# transformer "bez pamięci" - zrobi dokladnie to samo dla train set i test set
fix_type_transformer = FunctionTransformer(fix_type, validate=False)

#fixed_train = fix_type_transformer.fit_transform(train)
#fixed_test = fix_type_transformer.fit_transform(test)

In [163]:
# transformer "z pamięcia"
# konieczne gdy feature w train i test mają inne charakterystyki
class FilterBinaryOutliers(TransformerMixin):
    def __init__(self):
        self.min_count = 2
        self._excludes = []
        
    def fit(self, X, y=None, **kwargs):
        binary_selector = X.apply(lambda col: col.nunique()) <= 2
        nrows = X.shape[0]
        ol = X.loc[:,binary_selector].apply(lambda col: nrows - col.groupby(col).size().max() <= self.min_count )
        self._excludes = ol.index[ol]
        return self
    
    def transform(self, X, y=None, **kwargs):
        return X.drop(self._excludes, axis=1)
    
    # niepotrzebne:
    def get_params(self, deep=True):
        return { "excluded_columns" : self._excludes }
    
tmp_train = pd.DataFrame({
    'col1': [0, 0, 0, 1, 1, 1],
    'col2': [0, 1, 1, 1, 1, 1]
})
tmp_test = pd.DataFrame({
    'col1': [0, 0, 0, 0, 1, 1],
    'col2': [0, 0, 0, 1, 1, 1]
})

f = FilterBinaryOutliers()
f.fit(tmp_train)
f.transform(tmp_test)

   col1
0     0
1     0
2     0
3     0
4     1
5     1

In [187]:
numeric_pipeline = Pipeline([
    ('SelectNumeric', FunctionTransformer(lambda df: df.select_dtypes(include=[np.number]), validate=False)),
    ('FillNA', FunctionTransformer(lambda df: df.fillna(-1), validate=False)),
    ('Normalize', MinMaxScaler())
])

categoric_pipeline = Pipeline([
    ('SelectCategoric', FunctionTransformer(lambda df: df.select_dtypes(exclude=[np.number]), validate=False)),
    # z "pamięcia" zapamiętującą w fazie fit
    ('OHE', OneHotEncoder(handle_unknown='ignore', return_df=True)),
    ('FilterOutliers', FilterBinaryOutliers())
])

feature_union = FeatureUnion([
    ('numeric', numeric_pipeline),
    ('categoric', categoric_pipeline),
])

transform_pipeline = Pipeline([
    ("FixType", fix_type_transformer),
    ("TransformData", feature_union)
])

#### Trening i walidacja

In [165]:
from sklearn.model_selection import train_test_split
# dużo, dużo więcej możliwości walidacji modelu: 
# http://scikit-learn.org/stable/modules/classes.html#module-sklearn.model_selection

X_train, X_valid, y_train, y_valid = train_test_split(train, y, test_size=0.25, shuffle=True)

In [166]:
from sklearn.linear_model import LogisticRegression

logreg_pipeline = Pipeline([
       ("Transform", transform_pipeline),
       ('Estimator', LogisticRegression()),
])

logreg_pipeline.fit(X_train, y_train)
prediction = logreg_pipeline.predict(X_valid)

# nie przejmować się SettingWithCopyWarning

/opt/anaconda2/envs/ml-sem/lib/python2.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [167]:
from sklearn.metrics import mean_squared_error
from math import sqrt

# Root-mean-square deviation
RMSD = sqrt(mean_squared_error(prediction, y_valid))
print("RMSD %f" % RMSD)

# na kagglu chcą RMSD z log
def kaggle_RMSD(prediction, true):
    prediction_log = map(sqrt, prediction)
    y_valid_log = map(sqrt, true)
    return sqrt(mean_squared_error(prediction_log, y_valid_log))

print("RMSD of logs %f" % kaggle_RMSD(prediction, y_valid))

RMSD 54891.311134
RMSD of logs 55.601081

### Tuning regresora - GridSearch + CV

In [226]:
## Tuning regresora
from sklearn.model_selection import GridSearchCV

params = {
    #'penalty' : ['l1', 'l2'],
    #'dual': [True, False],
    'tol': [1e-6, 1e-4, 1e-2],
    #'C': [0.8, 1.0, 1.2, 1.4],
    'fit_intercept': [True, False],  
}
# all listed here http://scikit-learn.org/stable/modules/model_evaluation.html
scoring = {'MSE': 'neg_mean_squared_error'}

gscv = GridSearchCV(LogisticRegression(), 
                    param_grid=params,
                    scoring='neg_mean_squared_error',
                    refit='neg_mean_squared_error',
                    n_jobs=5,
                    cv=4)

In [219]:
X_train_trans = transform_pipeline.fit_transform(X_train)
X_valid_trans = transform_pipeline.transform(X_valid)

gscv.fit(X_train_trans, y_train)
prediction = gscv.predict(X_valid_trans)
best_logreg = gscv.best_estimator_
best_logreg

/opt/anaconda2/envs/ml-sem/lib/python2.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/opt/anaconda2/envs/ml-sem/lib/python2.7/site-packages/sklearn/model_selection/_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=4.
  % (min_groups, self.n_splits)), Warning)

LogisticRegression(C=1.2, class_weight=None, dual=False, fit_intercept=False,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [227]:
# Alternatrywnie moglibyśmy zaprząc grid search BEZPOŚREDNIO do naszego pipeline'u jako estymator
# uwaga: tak nie da się wprost wyciągnąć znalezionych hiperparametrów przez GridSearch
logreg_tuned_pipeline = Pipeline([
       ("Transform", transform_pipeline),
       ('Estimator', gscv),
])

logreg_tuned_pipeline.fit(X_train, y_train)
prediction = logreg_tuned_pipeline.predict(X_valid)

/opt/anaconda2/envs/ml-sem/lib/python2.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [228]:
kaggle_RMSD(prediction, y_valid)

55.71208382618633

In [31]:
# final
logreg_pipeline.fit(train, y)
prediction = logreg_pipeline.predict(test)

In [74]:
def kaggle_save(test, prediction):
    result = pd.DataFrame({
            'Id': test.index, 
            'SalePrice': prediction
    })
    result.to_csv("final.csv", index=False)
    return result

### Neural Nets - Keras

In [33]:
import keras
from keras.layers import Input, Dense, Dropout, Concatenate
from keras import Model
from keras.callbacks import EarlyStopping
from sklearn.base import BaseEstimator
from sklearn.preprocessing import StandardScaler
from keras import metrics

Using TensorFlow backend.

In [100]:
def create_model(colnum=258):
	# create model
    inputs = Input(shape=(colnum,))
    dense1 = Dense(256, activation='relu')(inputs)
    dense1 = Dropout(0.5)(dense1)
    dense2 = Dense(256, activation='relu')(dense1)
    dense2 = Dropout(0.5)(dense2)
    output = Dense(1, activation='relu', name='output')(dense2)
    model = Model(inputs=[inputs], outputs=[output])
    # exploding gradient problem when sgd as optimizer
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=[metrics.mean_squared_error])
    return model


def create_model_3(colnum=258):
	# create model
    inputs = Input(shape=(colnum,))
    dense1 = Dense(256, activation='relu')(inputs)
    dense1 = Dropout(0.5)(dense1)
    dense2 = Dense(256, activation='relu')(dense1)
    dense2 = Dropout(0.5)(dense2)
    dense3 = Dense(128, activation='relu')(dense2)
    dense4 = Dense(32, activation='relu')(dense3)
    output = Dense(1, activation='relu', name='output')(dense4)
    model = Model(inputs=[inputs], outputs=[output])
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=[metrics.mean_squared_error])
    return model

`Input` reprezentuje warstwę wejściową. Musimy podać ilość neuronów, drugi wymiar możemy zostawić pusty - keras sam się go domyśli na podstawie rozmiaru batcha wejściowego.

'Dense' reprezentuje warstwę gęstą, tzn taką, w której każdy neuron jest połączony z każdym neuronem poprzedniej warstwy. W postaci macierzowej możemy zapisać to jako $Y = f(AX + b)$, gdzie $f$ jest funkcją aktywacji, $X$ jest macierzą obserwacji w poprzedniej warstwie, $A$ to macierz wag a $b$ to wektor biasów.

'Dropout' to operacja, w wyniku której odsetek neuronów jest tymczasowo zerowany podczas traningu. Dzięki temu model ma mniejszą tendencję do przeuczania się.

Ostatnia warstwa zawiera tylko jeden neuron - jest to odpowiedź zwracana przez model. Za pomocą funkcji sigmoidalnej skalujemy czystą odpowiedź na przedział [0, 1].

Model jest następnie "kompilowany" - zadawana jest funkcja straty, definiujemy algorytm optymalizacji oraz metryki zwracane podczas uczenia.

In [35]:
# mógłbym zawołać tak:
X_train_trans = transform_pipeline.fit_transform(X_train)
X_valid_trans = transform_pipeline.transform(X_valid)

/opt/anaconda2/envs/ml-sem/lib/python2.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [98]:
model = create_model_3(colnum=X_train_trans.shape[1])
model.fit([X_train_trans], [y_train], epochs=100, batch_size=32, verbose=1, validation_data=[[X_valid_trans], [y_valid]])

Train on 1095 samples, validate on 365 samples
Epoch 1/100
1095/1095 [==============================] - 1s 777us/step - loss: 39681227848.0073 - mean_squared_error: 39681227848.0073 - val_loss: 35350332042.8712 - val_mean_squared_error: 35350332042.8712
Epoch 2/100
1095/1095 [==============================] - 0s 135us/step - loss: 28616146707.4046 - mean_squared_error: 28616146707.4046 - val_loss: 6302613847.6712 - val_mean_squared_error: 6302613847.6712
Epoch 3/100
1095/1095 [==============================] - 0s 129us/step - loss: 5795549136.1315 - mean_squared_error: 5795549136.1315 - val_loss: 3230051388.3178 - val_mean_squared_error: 3230051388.3178
Epoch 4/100
1095/1095 [==============================] - 0s 122us/step - loss: 4063704175.8685 - mean_squared_error: 4063704175.8685 - val_loss: 2479185540.5589 - val_mean_squared_error: 2479185540.5589
Epoch 5/100
1095/1095 [==============================] - 0s 134us/step - loss: 3421463289.4539 - mean_squared_error: 3421463289.4539 - val_loss: 2008579273.2932 - val_mean_squared_error: 2008579273.2932
Epoch 6/100
1095/1095 [==============================] - 0s 130us/step - loss: 2882641032.6502 - mean_squared_error: 2882641032.6502 - val_loss: 1732459022.0274 - val_mean_squared_error: 1732459022.0274
Epoch 7/100
1095/1095 [==============================] - 0s 131us/step - loss: 2603477957.6694 - mean_squared_error: 2603477957.6694 - val_loss: 1543253578.3452 - val_mean_squared_error: 1543253578.3452
Epoch 8/100
1095/1095 [==============================] - 0s 146us/step - loss: 2284164427.2804 - mean_squared_error: 2284164427.2804 - val_loss: 1350996830.6849 - val_mean_squared_error: 1350996830.6849
Epoch 9/100
1095/1095 [==============================] - 0s 125us/step - loss: 2054457304.3726 - mean_squared_error: 2054457304.3726 - val_loss: 1227453369.1616 - val_mean_squared_error: 1227453369.1616
Epoch 10/100
1095/1095 [==============================] - 0s 121us/step - loss: 1896849685.1580 - mean_squared_error: 1896849685.1580 - val_loss: 1118340769.3151 - val_mean_squared_error: 1118340769.3151
Epoch 11/100
1095/1095 [==============================] - 0s 127us/step - loss: 1739502150.4877 - mean_squared_error: 1739502150.4877 - val_loss: 999605470.5096 - val_mean_squared_error: 999605470.5096
Epoch 12/100
1095/1095 [==============================] - 0s 123us/step - loss: 1783179445.4210 - mean_squared_error: 1783179445.4210 - val_loss: 933442495.8247 - val_mean_squared_error: 933442495.8247
Epoch 13/100
1095/1095 [==============================] - 0s 124us/step - loss: 1608322883.0977 - mean_squared_error: 1608322883.0977 - val_loss: 862933026.3671 - val_mean_squared_error: 862933026.3671
Epoch 14/100
1095/1095 [==============================] - 0s 121us/step - loss: 1513798878.4511 - mean_squared_error: 1513798878.4511 - val_loss: 822603183.1671 - val_mean_squared_error: 822603183.1671
Epoch 15/100
1095/1095 [==============================] - 0s 133us/step - loss: 1555061969.9434 - mean_squared_error: 1555061969.9434 - val_loss: 797861779.1123 - val_mean_squared_error: 797861779.1123
Epoch 16/100
1095/1095 [==============================] - 0s 127us/step - loss: 1486724823.3205 - mean_squared_error: 1486724823.3205 - val_loss: 879816674.6301 - val_mean_squared_error: 879816674.6301
Epoch 17/100
1095/1095 [==============================] - 0s 122us/step - loss: 1410382066.9297 - mean_squared_error: 1410382066.9297 - val_loss: 755745190.2247 - val_mean_squared_error: 755745190.2247
Epoch 18/100
1095/1095 [==============================] - 0s 121us/step - loss: 1439979827.7553 - mean_squared_error: 1439979827.7553 - val_loss: 754178861.1507 - val_mean_squared_error: 754178861.1507
Epoch 19/100
1095/1095 [==============================] - 0s 122us/step - loss: 1432040508.4347 - mean_squared_error: 1432040508.4347 - val_loss: 744107417.4247 - val_mean_squared_error: 744107417.4247
Epoch 20/100
1095/1095 [==============================] - 0s 125us/step - loss: 1388128807.9489 - mean_squared_error: 1388128807.9489 - val_loss: 772728606.4219 - val_mean_squared_error: 772728606.4219
Epoch 21/100
1095/1095 [==============================] - 0s 126us/step - loss: 1317400264.0950 - mean_squared_error: 1317400264.0950 - val_loss: 767421690.9151 - val_mean_squared_error: 767421690.9151
Epoch 22/100
1095/1095 [==============================] - 0s 144us/step - loss: 1465662926.6703 - mean_squared_error: 1465662926.6703 - val_loss: 840809889.5781 - val_mean_squared_error: 840809889.5781
Epoch 23/100
1095/1095 [==============================] - 0s 128us/step - loss: 1524744388.7050 - mean_squared_error: 1524744388.7050 - val_loss: 692369503.1233 - val_mean_squared_error: 692369503.1233
Epoch 24/100
1095/1095 [==============================] - 0s 121us/step - loss: 1559684519.7443 - mean_squared_error: 1559684519.7443 - val_loss: 684844200.0658 - val_mean_squared_error: 684844200.0658
Epoch 25/100
1095/1095 [==============================] - 0s 120us/step - loss: 1416167968.7598 - mean_squared_error: 1416167968.7598 - val_loss: 689111020.0986 - val_mean_squared_error: 689111020.0986
Epoch 26/100
1095/1095 [==============================] - 0s 122us/step - loss: 1262309862.7507 - mean_squared_error: 1262309862.7507 - val_loss: 670657587.6384 - val_mean_squared_error: 670657587.6384
Epoch 27/100
1095/1095 [==============================] - 0s 122us/step - loss: 1239618247.1306 - mean_squared_error: 1239618247.1306 - val_loss: 709799309.0630 - val_mean_squared_error: 709799309.0630
Epoch 28/100
1095/1095 [==============================] - 0s 119us/step - loss: 1226199211.1342 - mean_squared_error: 1226199211.1342 - val_loss: 657386114.8932 - val_mean_squared_error: 657386114.8932
Epoch 29/100
1095/1095 [==============================] - 0s 134us/step - loss: 1427568261.9032 - mean_squared_error: 1427568261.9032 - val_loss: 649465993.9945 - val_mean_squared_error: 649465993.9945
Epoch 30/100
1095/1095 [==============================] - 0s 126us/step - loss: 1371047012.1498 - mean_squared_error: 1371047012.1498 - val_loss: 675897317.0849 - val_mean_squared_error: 675897317.0849
Epoch 31/100
1095/1095 [==============================] - 0s 123us/step - loss: 1312590335.7078 - mean_squared_error: 1312590335.7078 - val_loss: 684636758.5315 - val_mean_squared_error: 684636758.5315
Epoch 32/100
1095/1095 [==============================] - 0s 122us/step - loss: 1233868554.9005 - mean_squared_error: 1233868554.9005 - val_loss: 707429034.9589 - val_mean_squared_error: 707429034.9589
Epoch 33/100
1095/1095 [==============================] - 0s 125us/step - loss: 1383356576.5991 - mean_squared_error: 1383356576.5991 - val_loss: 636515258.5644 - val_mean_squared_error: 636515258.5644
Epoch 34/100
1095/1095 [==============================] - 0s 121us/step - loss: 1136275589.8447 - mean_squared_error: 1136275589.8447 - val_loss: 690994313.9945 - val_mean_squared_error: 690994313.9945
Epoch 35/100
1095/1095 [==============================] - 0s 115us/step - loss: 1253573455.1963 - mean_squared_error: 1253573455.1963 - val_loss: 686362946.1041 - val_mean_squared_error: 686362946.1041
Epoch 36/100
1095/1095 [==============================] - 0s 128us/step - loss: 1208019235.1854 - mean_squared_error: 1208019235.1854 - val_loss: 629903651.3315 - val_mean_squared_error: 629903651.3315
Epoch 37/100
1095/1095 [==============================] - 0s 130us/step - loss: 1287866334.3342 - mean_squared_error: 1287866334.3342 - val_loss: 669979304.9425 - val_mean_squared_error: 669979304.9425
Epoch 38/100
1095/1095 [==============================] - 0s 125us/step - loss: 1224815585.0813 - mean_squared_error: 1224815585.0813 - val_loss: 664371842.1041 - val_mean_squared_error: 664371842.1041
Epoch 39/100
1095/1095 [==============================] - 0s 110us/step - loss: 1263097619.8941 - mean_squared_error: 1263097619.8941 - val_loss: 630981118.8603 - val_mean_squared_error: 630981118.8603
Epoch 40/100
1095/1095 [==============================] - 0s 116us/step - loss: 1219175957.8594 - mean_squared_error: 1219175957.8594 - val_loss: 681764571.2658 - val_mean_squared_error: 681764571.2658
Epoch 41/100
1095/1095 [==============================] - 0s 121us/step - loss: 1136890829.6767 - mean_squared_error: 1136890829.6767 - val_loss: 613782235.5288 - val_mean_squared_error: 613782235.5288
Epoch 42/100
1095/1095 [==============================] - 0s 121us/step - loss: 1219610331.3534 - mean_squared_error: 1219610331.3534 - val_loss: 624405650.4548 - val_mean_squared_error: 624405650.4548
Epoch 43/100
1095/1095 [==============================] - 0s 126us/step - loss: 1264188981.7717 - mean_squared_error: 1264188981.7717 - val_loss: 618299030.0932 - val_mean_squared_error: 618299030.0932
Epoch 44/100
1095/1095 [==============================] - 0s 141us/step - loss: 1178026420.7196 - mean_squared_error: 1178026420.7196 - val_loss: 648389124.9096 - val_mean_squared_error: 648389124.9096
Epoch 45/100
1095/1095 [==============================] - 0s 132us/step - loss: 1082583236.9680 - mean_squared_error: 1082583236.9680 - val_loss: 616228558.5534 - val_mean_squared_error: 616228558.5534
Epoch 46/100
1095/1095 [==============================] - 0s 127us/step - loss: 1151259726.6703 - mean_squared_error: 1151259726.6703 - val_loss: 638584154.6082 - val_mean_squared_error: 638584154.6082
Epoch 47/100
1095/1095 [==============================] - 0s 125us/step - loss: 1139498558.5388 - mean_squared_error: 1139498558.5388 - val_loss: 685901874.0164 - val_mean_squared_error: 685901874.0164
Epoch 48/100
1095/1095 [==============================] - 0s 132us/step - loss: 1050220711.2767 - mean_squared_error: 1050220711.2767 - val_loss: 648426810.4767 - val_mean_squared_error: 648426810.4767
Epoch 49/100
1095/1095 [==============================] - 0s 122us/step - loss: 1137844317.5160 - mean_squared_error: 1137844317.5160 - val_loss: 649668372.9096 - val_mean_squared_error: 649668372.9096
Epoch 50/100
1095/1095 [==============================] - 0s 128us/step - loss: 1150076024.4895 - mean_squared_error: 1150076024.4895 - val_loss: 657937561.6877 - val_mean_squared_error: 657937561.6877
Epoch 51/100
1095/1095 [==============================] - 0s 152us/step - loss: 1064190858.2868 - mean_squared_error: 1064190858.2868 - val_loss: 634056018.2795 - val_mean_squared_error: 634056018.2795
Epoch 52/100
1095/1095 [==============================] - 0s 134us/step - loss: 1017495830.6776 - mean_squared_error: 1017495830.6776 - val_loss: 604960524.4055 - val_mean_squared_error: 604960524.4055
Epoch 53/100
1095/1095 [==============================] - 0s 135us/step - loss: 1154132242.4694 - mean_squared_error: 1154132242.4694 - val_loss: 597207161.9507 - val_mean_squared_error: 597207161.9507
Epoch 54/100
1095/1095 [==============================] - 0s 129us/step - loss: 1115322379.2219 - mean_squared_error: 1115322379.2219 - val_loss: 613885340.2301 - val_mean_squared_error: 613885340.2301
Epoch 55/100
1095/1095 [==============================] - 0s 133us/step - loss: 1161616934.1662 - mean_squared_error: 1161616934.1662 - val_loss: 597079332.4274 - val_mean_squared_error: 597079332.4274
Epoch 56/100
1095/1095 [==============================] - 0s 131us/step - loss: 1149223551.3571 - mean_squared_error: 1149223551.3571 - val_loss: 605580109.6329 - val_mean_squared_error: 605580109.6329
Epoch 57/100
1095/1095 [==============================] - 0s 141us/step - loss: 1080833550.3927 - mean_squared_error: 1080833550.3927 - val_loss: 612120454.1808 - val_mean_squared_error: 612120454.1808
Epoch 58/100
1095/1095 [==============================] - 0s 149us/step - loss: 982226187.6749 - mean_squared_error: 982226187.6749 - val_loss: 604550255.2986 - val_mean_squared_error: 604550255.2986
Epoch 59/100
1095/1095 [==============================] - 0s 126us/step - loss: 1080984205.1507 - mean_squared_error: 1080984205.1507 - val_loss: 594831249.0082 - val_mean_squared_error: 594831249.0082
Epoch 60/100
1095/1095 [==============================] - 0s 127us/step - loss: 1152116236.7123 - mean_squared_error: 1152116236.7123 - val_loss: 635651069.0192 - val_mean_squared_error: 635651069.0192
Epoch 61/100
1095/1095 [==============================] - 0s 125us/step - loss: 1021038622.1005 - mean_squared_error: 1021038622.1005 - val_loss: 587928073.9507 - val_mean_squared_error: 587928073.9507
Epoch 62/100
1095/1095 [==============================] - 0s 125us/step - loss: 969848982.7945 - mean_squared_error: 969848982.7945 - val_loss: 588730233.3808 - val_mean_squared_error: 588730233.3808
Epoch 63/100
1095/1095 [==============================] - 0s 129us/step - loss: 982199832.7817 - mean_squared_error: 982199832.7817 - val_loss: 596682141.2822 - val_mean_squared_error: 596682141.2822
Epoch 64/100
1095/1095 [==============================] - 0s 143us/step - loss: 1088754252.5954 - mean_squared_error: 1088754252.5954 - val_loss: 585188367.2110 - val_mean_squared_error: 585188367.2110
Epoch 65/100
1095/1095 [==============================] - 0s 137us/step - loss: 1116816639.0648 - mean_squared_error: 1116816639.0648 - val_loss: 594745006.7726 - val_mean_squared_error: 594745006.7726
Epoch 66/100
1095/1095 [==============================] - 0s 133us/step - loss: 1029316956.2740 - mean_squared_error: 1029316956.2740 - val_loss: 607719906.3233 - val_mean_squared_error: 607719906.3233
Epoch 67/100
1095/1095 [==============================] - 0s 136us/step - loss: 957497637.4356 - mean_squared_error: 957497637.4356 - val_loss: 607771900.3178 - val_mean_squared_error: 607771900.3178
Epoch 68/100
1095/1095 [==============================] - 0s 130us/step - loss: 1045082123.5726 - mean_squared_error: 1045082123.5726 - val_loss: 695447308.7123 - val_mean_squared_error: 695447308.7123
Epoch 69/100
1095/1095 [==============================] - 0s 126us/step - loss: 1028702817.5489 - mean_squared_error: 1028702817.5489 - val_loss: 588454837.8301 - val_mean_squared_error: 588454837.8301
Epoch 70/100
1095/1095 [==============================] - 0s 128us/step - loss: 975345486.8311 - mean_squared_error: 975345486.8311 - val_loss: 623627946.5205 - val_mean_squared_error: 623627946.5205
Epoch 71/100
1095/1095 [==============================] - 0s 144us/step - loss: 951153635.0977 - mean_squared_error: 951153635.0977 - val_loss: 580246999.5397 - val_mean_squared_error: 580246999.5397
Epoch 72/100
1095/1095 [==============================] - 0s 140us/step - loss: 955529372.3470 - mean_squared_error: 955529372.3470 - val_loss: 566904562.4986 - val_mean_squared_error: 566904562.4986
Epoch 73/100
1095/1095 [==============================] - 0s 148us/step - loss: 1035119363.2731 - mean_squared_error: 1035119363.2731 - val_loss: 576048048.2192 - val_mean_squared_error: 576048048.2192
Epoch 74/100
1095/1095 [==============================] - 0s 135us/step - loss: 1069800586.9005 - mean_squared_error: 1069800586.9005 - val_loss: 610169989.3479 - val_mean_squared_error: 610169989.3479
Epoch 75/100
1095/1095 [==============================] - 0s 197us/step - loss: 962189475.7699 - mean_squared_error: 962189475.7699 - val_loss: 572767592.6356 - val_mean_squared_error: 572767592.6356
Epoch 76/100
1095/1095 [==============================] - 0s 199us/step - loss: 1002401393.3881 - mean_squared_error: 1002401393.3881 - val_loss: 551267876.6027 - val_mean_squared_error: 551267876.6027
Epoch 77/100
1095/1095 [==============================] - 0s 220us/step - loss: 1042961751.0868 - mean_squared_error: 1042961751.0868 - val_loss: 549109992.3288 - val_mean_squared_error: 549109992.3288
Epoch 78/100
1095/1095 [==============================] - 0s 201us/step - loss: 1081434881.8995 - mean_squared_error: 1081434881.8995 - val_loss: 577351993.3808 - val_mean_squared_error: 577351993.3808
Epoch 79/100
1095/1095 [==============================] - 0s 195us/step - loss: 1076212394.9151 - mean_squared_error: 1076212394.9151 - val_loss: 559013188.2082 - val_mean_squared_error: 559013188.2082
Epoch 80/100
1095/1095 [==============================] - 0s 195us/step - loss: 1005229163.0904 - mean_squared_error: 1005229163.0904 - val_loss: 546068204.8877 - val_mean_squared_error: 546068204.8877
Epoch 81/100
1095/1095 [==============================] - 0s 216us/step - loss: 889874539.0174 - mean_squared_error: 889874539.0174 - val_loss: 570587936.7452 - val_mean_squared_error: 570587936.7452

Epoch 82/100
1095/1095 [==============================] - 0s 206us/step - loss: 890954816.9936 - mean_squared_error: 890954816.9936 - val_loss: 563549682.2356 - val_mean_squared_error: 563549682.2356
Epoch 83/100
1095/1095 [==============================] - 0s 201us/step - loss: 874352896.0731 - mean_squared_error: 874352896.0731 - val_loss: 585385582.2466 - val_mean_squared_error: 585385582.2466
Epoch 84/100
1095/1095 [==============================] - 0s 198us/step - loss: 1020958069.1142 - mean_squared_error: 1020958069.1142 - val_loss: 546793020.3178 - val_mean_squared_error: 546793020.3178
Epoch 85/100
1095/1095 [==============================] - 0s 207us/step - loss: 973146333.2822 - mean_squared_error: 973146333.2822 - val_loss: 589187772.7123 - val_mean_squared_error: 589187772.7123
Epoch 86/100
1095/1095 [==============================] - 0s 222us/step - loss: 916915106.3379 - mean_squared_error: 916915106.3379 - val_loss: 590886130.4986 - val_mean_squared_error: 590886130.4986
Epoch 87/100
1095/1095 [==============================] - 0s 201us/step - loss: 1006638121.9068 - mean_squared_error: 1006638121.9068 - val_loss: 659068773.8301 - val_mean_squared_error: 659068773.8301
Epoch 88/100
1095/1095 [==============================] - 0s 198us/step - loss: 892015307.2804 - mean_squared_error: 892015307.2804 - val_loss: 575953558.8384 - val_mean_squared_error: 575953558.8384
Epoch 89/100
1095/1095 [==============================] - 0s 201us/step - loss: 927313757.1653 - mean_squared_error: 927313757.1653 - val_loss: 602742749.0630 - val_mean_squared_error: 602742749.0630
Epoch 90/100
1095/1095 [==============================] - 0s 229us/step - loss: 1046230114.6009 - mean_squared_error: 1046230114.6009 - val_loss: 582965735.1014 - val_mean_squared_error: 582965735.1014
Epoch 91/100
1095/1095 [==============================] - 0s 199us/step - loss: 932072957.5890 - mean_squared_error: 932072957.5890 - val_loss: 566920213.8740 - val_mean_squared_error: 566920213.8740
Epoch 92/100
1095/1095 [==============================] - 0s 171us/step - loss: 885810499.2146 - mean_squared_error: 885810499.2146 - val_loss: 618491262.3342 - val_mean_squared_error: 618491262.3342
Epoch 93/100
1095/1095 [==============================] - 0s 125us/step - loss: 930578256.0146 - mean_squared_error: 930578256.0146 - val_loss: 546767070.1589 - val_mean_squared_error: 546767070.1589
Epoch 94/100
1095/1095 [==============================] - 0s 121us/step - loss: 854162785.8995 - mean_squared_error: 854162785.8995 - val_loss: 591412654.0274 - val_mean_squared_error: 591412654.0274
Epoch 95/100
1095/1095 [==============================] - 0s 130us/step - loss: 914320347.7626 - mean_squared_error: 914320347.7626 - val_loss: 522816855.8027 - val_mean_squared_error: 522816855.8027
Epoch 96/100
1095/1095 [==============================] - 0s 130us/step - loss: 911710995.6968 - mean_squared_error: 911710995.6968 - val_loss: 519511683.0247 - val_mean_squared_error: 519511683.0247
Epoch 97/100
1095/1095 [==============================] - 0s 122us/step - loss: 962792109.4429 - mean_squared_error: 962792109.4429 - val_loss: 551721469.4575 - val_mean_squared_error: 551721469.4575
Epoch 98/100
1095/1095 [==============================] - 0s 122us/step - loss: 884874305.5196 - mean_squared_error: 884874305.5196 - val_loss: 518083145.6000 - val_mean_squared_error: 518083145.6000
Epoch 99/100
1095/1095 [==============================] - 0s 121us/step - loss: 890538564.3836 - mean_squared_error: 890538564.3836 - val_loss: 524172474.5205 - val_mean_squared_error: 524172474.5205
Epoch 100/100
1095/1095 [==============================] - 0s 132us/step - loss: 922530166.2977 - mean_squared_error: 922530166.2977 - val_loss: 531054085.3479 - val_mean_squared_error: 531054085.3479

In [99]:
nn_predict = model.predict(X_valid_trans).flatten()
kaggle_RMSD(nn_predict, y_valid)

25.97869574321095

In [95]:
# prepare final submission for kaggle:
train_trans = transform_pipeline.fit_transform(train)
test_trans = transform_pipeline.transform(test)
model = create_model_3(colnum=train_trans.shape[1])
model.fit([train_trans], [y], epochs=400, batch_size=32, verbose=0)
nn_predict = model.predict(test_trans).flatten()

In [96]:
kaggle_save(test, nn_predict)

        Id      SalePrice
0     1461  121975.085938
1     1462  149423.015625
2     1463  175245.843750
3     1464  193364.343750
4     1465  183697.609375
5     1466  165606.500000
6     1467  172794.718750
7     1468  159737.921875
8     1469  172448.125000
9     1470  122740.132812
10    1471  153671.953125
11    1472  101543.835938
12    1473   98294.070312
13    1474  141873.109375
14    1475  108828.734375
15    1476  361187.937500
16    1477  247145.234375
17    1478  284848.750000
18    1479  308898.437500
19    1480  523832.812500
20    1481  310964.593750
21    1482  203509.687500
22    1483  171377.343750
23    1484  166482.500000
24    1485  188383.671875
25    1486  185752.531250
26    1487  302704.125000
27    1488  217957.781250
28    1489  192685.437500
29    1490  240210.437500
...    ...            ...
1429  2890   81128.820312
1430  2891  137528.546875
1431  2892   19974.798828
1432  2893   43905.085938
1433  2894   38270.828125
1434  2895  426402.812500
1435  2896  271271.156250
1436  2897  189498.578125
1437  2898  143811.156250
1438  2899  193531.875000
1439  2900  163344.828125
1440  2901  242380.812500
1441  2902  185076.562500
1442  2903  308384.187500
1443  2904  334854.812500
1444  2905   70731.242188
1445  2906  190007.531250
1446  2907  102186.773438
1447  2908  140614.125000
1448  2909  142102.656250
1449  2910   77043.226562
1450  2911   78063.179688
1451  2912  152263.468750
1452  2913   73950.085938
1453  2914   75273.515625
1454  2915   74909.882812
1455  2916   77042.835938
1456  2917  158524.406250
1457  2918  110790.742188
1458  2919  207759.093750

[1459 rows x 2 columns]

In [ ]:
# ale mozemy takze wpleść model w nasz pipeline

from keras.wrappers.scikit_learn import KerasRegressor

nn_model = KerasRegressor(build_fn=create_model_3, epochs=10, batch_size=32, verbose=1)

full_pipeline = Pipeline([
       ("Transform", transform_pipeline),
       ('Estimator', nn_model),
])

full_pipeline.fit(x_train, y)
prediction = full_pipeline.predict(X_valid)